[package]
name = "ot_dalek"
version = "0.1.0"
authors = ["Michele Orrù <michele.orru@ens.fr>"]
keywords = ["cryptography", "curve25519", "oblivious-transfer"]
description = "SimpleOT from Orlandi and Chou in pure-Rust, using curve25519-dalek."

[dependencies]
curve25519-dalek = "1"
rand = "0.6.1"
digest = "0.8.0"
generic-array = "0.12.0"

[dev-dependencies]
criterion = "0.2"
sha2 = "0.8.0"

[[bench]]
name = "ot_benchmarks"
harness = false